retool serializer to be built by stage0 rustc

diff --git a/src/etc/gen-astencode b/src/etc/gen-astencode
--- a/src/etc/gen-astencode
+++ b/src/etc/gen-astencode
@@ -5,11 +5,16 @@ GEN_TYPES="syntax::ast::item syntax::ast::def middle::typeck::method_origin \
            middle::freevars::freevar_entry syntax::ast::def_id"
 
 # Find serializer tool:
-for S in build/*/stage2/bin/serializer; do
+for S in build/*/stage1/bin/serializer; do
+
+    if [ ! -x "$S" ]; then
+        echo "serializer excutable not found; try 'make serializer'"
+        exit 1
+    fi
 
     # Find rustc:
     D=$(dirname "$S")
-    R="${D}/rustc"
+    R="${D}/../../stage0/bin/rustc"
     if [ ! -x "$R" ]; then
         echo "rustc not found or not executable at path '$R'"
         exit 1
