Disable rust master toolchain build temporarily

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -75,13 +75,14 @@ matrix:
     - os: windows
 
 script:
-  - |
-      rm rust-toolchain
-      cargo install rustup-toolchain-install-master || echo "rustup-toolchain-install-master already installed"
-      RUSTC_HASH=$(git ls-remote https://github.com/rust-lang/rust.git master | awk '{print $1}')
-      travis_retry rustup-toolchain-install-master -f -n master $RUSTC_HASH
-      rustup default master
-      export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib
+  # uncomment once https://github.com/rust-lang/rust/issues/55376 is fixed
+  # - |
+  #     rm rust-toolchain
+  #     cargo install rustup-toolchain-install-master || echo "rustup-toolchain-install-master already installed"
+  #     RUSTC_HASH=$(git ls-remote https://github.com/rust-lang/rust.git master | awk '{print $1}')
+  #     travis_retry rustup-toolchain-install-master -f -n master $RUSTC_HASH
+  #     rustup default master
+  #     export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib
   - |
     if [ -z ${INTEGRATION} ]; then
       ./ci/base-tests.sh && sleep 5
