Fixed cross-crate generic call test to compile lib and bin separately
The original test produced a single crate with two mods, which was not
the goal of the test.

diff --git a/src/test/run-make-fulldeps/coverage-spanview/Makefile b/src/test/run-make-fulldeps/coverage-spanview/Makefile
--- a/src/test/run-make-fulldeps/coverage-spanview/Makefile
+++ b/src/test/run-make-fulldeps/coverage-spanview/Makefile
@@ -21,7 +21,7 @@ endef
 export SPANVIEW_HEADER
 
 ifeq ($(LLVM_VERSION_11_PLUS),true)
-all: $(patsubst $(SOURCEDIR)/%.rs,%,$(wildcard $(SOURCEDIR)/*.rs))
+all: $(patsubst $(SOURCEDIR)/lib/%.rs,%,$(wildcard $(SOURCEDIR)/lib/*.rs)) $(patsubst $(SOURCEDIR)/%.rs,%,$(wildcard $(SOURCEDIR)/*.rs))
 else
 $(info Rust option `-Z instrument-coverage` requires LLVM 11 or higher. Test skipped.)
 all:
@@ -36,12 +36,47 @@ endif
 
 -include clear_expected_if_blessed
 
+# FIXME(richkadel): The actions for these two types of targets (libraries and binaries) should be
+# combined.
+
+%: $(SOURCEDIR)/lib/%.rs
+	# Compile the test library with coverage instrumentation
+	$(RUSTC) $(SOURCEDIR)/lib/$@.rs \
+			$$( grep -q '^\/\/ require-rust-edition-2018' $(SOURCEDIR)/lib/$@.rs && \
+				echo "--edition=2018" \
+			) \
+			--crate-type rlib \
+			-Zinstrument-coverage \
+			-Zdump-mir=InstrumentCoverage \
+			-Zdump-mir-spanview \
+			-Zdump-mir-dir="$(TMPDIR)"/mir_dump.$@
+
+	for path in "$(TMPDIR)"/mir_dump.$@/*; do \
+		file="$$(basename "$$path")"; \
+		urlescaped="$$("$(PYTHON)" $(BASEDIR)/escape_url.py $$file)" || exit $$?; \
+		printf "$$SPANVIEW_HEADER\n" "$@" "$$urlescaped" > "$$path".modified; \
+		tail -n +2 "$$path" >> "$$path".modified; \
+		mv "$$path".modified "$$path"; \
+	done && true # for/done ends in non-zero status
+
+ifdef RUSTC_BLESS_TEST
+	mkdir -p expected_mir_dump.$@
+	cp "$(TMPDIR)"/mir_dump.$@/*InstrumentCoverage.0.html expected_mir_dump.$@/
+else
+	# Check that the selected `mir_dump` files match what we expect (`--bless` refreshes `expected`)
+	mkdir -p "$(TMPDIR)"/actual_mir_dump.$@
+	rm -f "$(TMPDIR)"/actual_mir_dump.$@/*
+	cp "$(TMPDIR)"/mir_dump.$@/*InstrumentCoverage.0.html "$(TMPDIR)"/actual_mir_dump.$@/
+	$(DIFF) -r expected_mir_dump.$@/ "$(TMPDIR)"/actual_mir_dump.$@/
+endif
+
 %: $(SOURCEDIR)/%.rs
-	# Compile the test program with coverage instrumentation and generate relevant MIR.
+	# Compile the test program with coverage instrumentation
 	$(RUSTC) $(SOURCEDIR)/$@.rs \
 			$$( grep -q '^\/\/ require-rust-edition-2018' $(SOURCEDIR)/$@.rs && \
 				echo "--edition=2018" \
 			) \
+			-L "$(TMPDIR)" \
 			-Zinstrument-coverage \
 			-Zdump-mir=InstrumentCoverage \
 			-Zdump-mir-spanview \
