check build time on ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -117,193 +117,201 @@ jobs:
         with:
           fetch-depth: 2
 
-      # Free up disk space on Linux by removing preinstalled components that
-      # we do not need. We do this to enable some of the less resource
-      # intensive jobs to run on free runners, which however also have
-      # less disk space.
-      - name: free up disk space
-        run: src/ci/scripts/free-disk-space-linux.sh
-        if: matrix.free_disk
+      # Clear cargo cache between runs to avoid cache effects
+      - name: clear cargo cache
+        run: rm -rf ~/.cargo/registry ~/.cargo/git /tmp/cargo-install
 
-      # If we don't need to free up disk space then just report how much space we have
-      - name: print disk usage
-        run: |
-          echo "disk usage:"
-          df -h
-        if: matrix.free_disk == false
+      # Measure build time of tidy
+      - name: build tidy
+        run: cd ./src/tools/tidy && cargo clean && time cargo build --quiet
 
-      # Rust Log Analyzer can't currently detect the PR number of a GitHub
-      # Actions build on its own, so a hint in the log message is needed to
-      # point it in the right direction.
-      - name: configure the PR in which the error message will be posted
-        run: echo "[CI_PR_NUMBER=$num]"
-        env:
-          num: ${{ github.event.number }}
-        if: needs.calculate_matrix.outputs.run_type == 'pr'
+  #     # Free up disk space on Linux by removing preinstalled components that
+  #     # we do not need. We do this to enable some of the less resource
+  #     # intensive jobs to run on free runners, which however also have
+  #     # less disk space.
+  #     - name: free up disk space
+  #       run: src/ci/scripts/free-disk-space-linux.sh
+  #       if: matrix.free_disk
 
-      - name: add extra environment variables
-        run: src/ci/scripts/setup-environment.sh
-        env:
-          # Since it's not possible to merge `${{ matrix.env }}` with the other
-          # variables in `job.<name>.env`, the variables defined in the matrix
-          # are passed to the `setup-environment.sh` script encoded in JSON,
-          # which then uses log commands to actually set them.
-          EXTRA_VARIABLES: ${{ toJson(matrix.env) }}
+  #     # If we don't need to free up disk space then just report how much space we have
+  #     - name: print disk usage
+  #       run: |
+  #         echo "disk usage:"
+  #         df -h
+  #       if: matrix.free_disk == false
 
-      - name: ensure the channel matches the target branch
-        run: src/ci/scripts/verify-channel.sh
+  #     # Rust Log Analyzer can't currently detect the PR number of a GitHub
+  #     # Actions build on its own, so a hint in the log message is needed to
+  #     # point it in the right direction.
+  #     - name: configure the PR in which the error message will be posted
+  #       run: echo "[CI_PR_NUMBER=$num]"
+  #       env:
+  #         num: ${{ github.event.number }}
+  #       if: needs.calculate_matrix.outputs.run_type == 'pr'
 
-      - name: collect CPU statistics
-        run: src/ci/scripts/collect-cpu-stats.sh
+  #     - name: add extra environment variables
+  #       run: src/ci/scripts/setup-environment.sh
+  #       env:
+  #         # Since it's not possible to merge `${{ matrix.env }}` with the other
+  #         # variables in `job.<name>.env`, the variables defined in the matrix
+  #         # are passed to the `setup-environment.sh` script encoded in JSON,
+  #         # which then uses log commands to actually set them.
+  #         EXTRA_VARIABLES: ${{ toJson(matrix.env) }}
 
-      - name: show the current environment
-        run: src/ci/scripts/dump-environment.sh
+  #     - name: ensure the channel matches the target branch
+  #       run: src/ci/scripts/verify-channel.sh
 
-      - name: install awscli
-        run: src/ci/scripts/install-awscli.sh
+  #     - name: collect CPU statistics
+  #       run: src/ci/scripts/collect-cpu-stats.sh
 
-      - name: install sccache
-        run: src/ci/scripts/install-sccache.sh
+  #     - name: show the current environment
+  #       run: src/ci/scripts/dump-environment.sh
 
-      - name: select Xcode
-        run: src/ci/scripts/select-xcode.sh
+  #     - name: install awscli
+  #       run: src/ci/scripts/install-awscli.sh
 
-      - name: install clang
-        run: src/ci/scripts/install-clang.sh
+  #     - name: install sccache
+  #       run: src/ci/scripts/install-sccache.sh
 
-      - name: install tidy
-        run: src/ci/scripts/install-tidy.sh
+  #     - name: select Xcode
+  #       run: src/ci/scripts/select-xcode.sh
 
-      - name: install WIX
-        run: src/ci/scripts/install-wix.sh
+  #     - name: install clang
+  #       run: src/ci/scripts/install-clang.sh
 
-      - name: disable git crlf conversion
-        run: src/ci/scripts/disable-git-crlf-conversion.sh
+  #     - name: install tidy
+  #       run: src/ci/scripts/install-tidy.sh
 
-      - name: checkout submodules
-        run: src/ci/scripts/checkout-submodules.sh
+  #     - name: install WIX
+  #       run: src/ci/scripts/install-wix.sh
 
-      - name: install MinGW
-        run: src/ci/scripts/install-mingw.sh
+  #     - name: disable git crlf conversion
+  #       run: src/ci/scripts/disable-git-crlf-conversion.sh
 
-      - name: install ninja
-        run: src/ci/scripts/install-ninja.sh
+  #     - name: checkout submodules
+  #       run: src/ci/scripts/checkout-submodules.sh
 
-      - name: enable ipv6 on Docker
-        # Don't run on codebuild because systemctl is not available
-        if: ${{ !matrix.codebuild }}
-        run: src/ci/scripts/enable-docker-ipv6.sh
+  #     - name: install MinGW
+  #       run: src/ci/scripts/install-mingw.sh
 
-      # Disable automatic line ending conversion (again). On Windows, when we're
-      # installing dependencies, something switches the git configuration directory or
-      # re-enables autocrlf. We've not tracked down the exact cause -- and there may
-      # be multiple -- but this should ensure submodules are checked out with the
-      # appropriate line endings.
-      - name: disable git crlf conversion
-        run: src/ci/scripts/disable-git-crlf-conversion.sh
+  #     - name: install ninja
+  #       run: src/ci/scripts/install-ninja.sh
 
-      - name: ensure line endings are correct
-        run: src/ci/scripts/verify-line-endings.sh
+  #     - name: enable ipv6 on Docker
+  #       # Don't run on codebuild because systemctl is not available
+  #       if: ${{ !matrix.codebuild }}
+  #       run: src/ci/scripts/enable-docker-ipv6.sh
 
-      - name: ensure backported commits are in upstream branches
-        run: src/ci/scripts/verify-backported-commits.sh
+  #     # Disable automatic line ending conversion (again). On Windows, when we're
+  #     # installing dependencies, something switches the git configuration directory or
+  #     # re-enables autocrlf. We've not tracked down the exact cause -- and there may
+  #     # be multiple -- but this should ensure submodules are checked out with the
+  #     # appropriate line endings.
+  #     - name: disable git crlf conversion
+  #       run: src/ci/scripts/disable-git-crlf-conversion.sh
 
-      - name: ensure the stable version number is correct
-        run: src/ci/scripts/verify-stable-version-number.sh
+  #     - name: ensure line endings are correct
+  #       run: src/ci/scripts/verify-line-endings.sh
 
-      # Show the environment just before we run the build
-      # This makes it easier to diagnose problems with the above install scripts.
-      - name: show the current environment
-        run: src/ci/scripts/dump-environment.sh
+  #     - name: ensure backported commits are in upstream branches
+  #       run: src/ci/scripts/verify-backported-commits.sh
 
-      # Pre-build citool before the following step uninstalls rustup
-      # Build it into the build directory, to avoid modifying sources
-      - name: build citool
-        run: |
-          cd src/ci/citool
-          CARGO_INCREMENTAL=0 CARGO_TARGET_DIR=../../../build/citool cargo build
+  #     - name: ensure the stable version number is correct
+  #       run: src/ci/scripts/verify-stable-version-number.sh
 
-      - name: run the build
-        run: |
-          set +e
-          # Redirect stderr to stdout to avoid reordering the two streams in the GHA logs.
-          src/ci/scripts/run-build-from-ci.sh 2>&1
-          STATUS=$?
-          set -e
+  #     # Show the environment just before we run the build
+  #     # This makes it easier to diagnose problems with the above install scripts.
+  #     - name: show the current environment
+  #       run: src/ci/scripts/dump-environment.sh
 
-          if [[ "$STATUS" -ne 0 && -n "$CI_JOB_DOC_URL" ]]; then
-            echo "****************************************************************************"
-            echo "To find more information about this job, visit the following URL:"
-            echo "$CI_JOB_DOC_URL"
-            echo "****************************************************************************"
-          fi
-          exit ${STATUS}
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.CACHES_AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.CACHES_AWS_SECRET_ACCESS_KEY }}
+  #     # Pre-build citool before the following step uninstalls rustup
+  #     # Build it into the build directory, to avoid modifying sources
+  #     - name: build citool
+  #       run: |
+  #         cd src/ci/citool
+  #         CARGO_INCREMENTAL=0 CARGO_TARGET_DIR=../../../build/citool cargo build
 
-      - name: create github artifacts
-        run: src/ci/scripts/create-doc-artifacts.sh
+  #     - name: run the build
+  #       run: |
+  #         set +e
+  #         # Redirect stderr to stdout to avoid reordering the two streams in the GHA logs.
+  #         src/ci/scripts/run-build-from-ci.sh 2>&1
+  #         STATUS=$?
+  #         set -e
 
-      - name: print disk usage
-        # We also want to know the disk usage when the job fails.
-        if: always()
-        run: |
-          echo "disk usage:"
-          df -h
+  #         if [[ "$STATUS" -ne 0 && -n "$CI_JOB_DOC_URL" ]]; then
+  #           echo "****************************************************************************"
+  #           echo "To find more information about this job, visit the following URL:"
+  #           echo "$CI_JOB_DOC_URL"
+  #           echo "****************************************************************************"
+  #         fi
+  #         exit ${STATUS}
+  #       env:
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.CACHES_AWS_ACCESS_KEY_ID }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.CACHES_AWS_SECRET_ACCESS_KEY }}
 
-      - name: upload artifacts to github
-        uses: actions/upload-artifact@v4
-        with:
-          # name is set in previous step
-          name: ${{ env.DOC_ARTIFACT_NAME }}
-          path: obj/artifacts/doc
-          if-no-files-found: ignore
-          retention-days: 5
+  #     - name: create github artifacts
+  #       run: src/ci/scripts/create-doc-artifacts.sh
 
-      - name: upload artifacts to S3
-        run: src/ci/scripts/upload-artifacts.sh
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_AWS_SECRET_ACCESS_KEY }}
-        # Adding a condition on DEPLOY=1 or DEPLOY_ALT=1 is not needed as all deploy
-        # builders *should* have the AWS credentials available. Still, explicitly
-        # adding the condition is helpful as this way CI will not silently skip
-        # deploying artifacts from a dist builder if the variables are misconfigured,
-        # erroring about invalid credentials instead.
-        if: github.event_name == 'push' || env.DEPLOY == '1' || env.DEPLOY_ALT == '1'
+  #     - name: print disk usage
+  #       # We also want to know the disk usage when the job fails.
+  #       if: always()
+  #       run: |
+  #         echo "disk usage:"
+  #         df -h
 
-      - name: postprocess metrics into the summary
-        # This step is not critical, and if some I/O problem happens, we don't want
-        # to cancel the build.
-        continue-on-error: true
-        run: |
-          if [ -f build/metrics.json ]; then
-            METRICS=build/metrics.json
-          elif [ -f obj/build/metrics.json ]; then
-            METRICS=obj/build/metrics.json
-          else
-            echo "No metrics.json found"
-            exit 0
-          fi
+  #     - name: upload artifacts to github
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         # name is set in previous step
+  #         name: ${{ env.DOC_ARTIFACT_NAME }}
+  #         path: obj/artifacts/doc
+  #         if-no-files-found: ignore
+  #         retention-days: 5
 
-          # Get closest bors merge commit
-          PARENT_COMMIT=`git rev-list --author='bors@rust-lang.org' --author='122020455+rust-bors\[bot\]@users.noreply.github.com' -n1 --first-parent HEAD^1`
+  #     - name: upload artifacts to S3
+  #       run: src/ci/scripts/upload-artifacts.sh
+  #       env:
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_AWS_ACCESS_KEY_ID }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_AWS_SECRET_ACCESS_KEY }}
+  #       # Adding a condition on DEPLOY=1 or DEPLOY_ALT=1 is not needed as all deploy
+  #       # builders *should* have the AWS credentials available. Still, explicitly
+  #       # adding the condition is helpful as this way CI will not silently skip
+  #       # deploying artifacts from a dist builder if the variables are misconfigured,
+  #       # erroring about invalid credentials instead.
+  #       if: github.event_name == 'push' || env.DEPLOY == '1' || env.DEPLOY_ALT == '1'
 
-          ./build/citool/debug/citool postprocess-metrics \
-              --job-name ${CI_JOB_NAME} \
-              --parent ${PARENT_COMMIT} \
-              ${METRICS} >> ${GITHUB_STEP_SUMMARY}
+  #     - name: postprocess metrics into the summary
+  #       # This step is not critical, and if some I/O problem happens, we don't want
+  #       # to cancel the build.
+  #       continue-on-error: true
+  #       run: |
+  #         if [ -f build/metrics.json ]; then
+  #           METRICS=build/metrics.json
+  #         elif [ -f obj/build/metrics.json ]; then
+  #           METRICS=obj/build/metrics.json
+  #         else
+  #           echo "No metrics.json found"
+  #           exit 0
+  #         fi
 
-      - name: upload job metrics to DataDog
-        # This step is not critical, and if some I/O problem happens, we don't want
-        # to cancel the build.
-        continue-on-error: true
-        if: needs.calculate_matrix.outputs.run_type != 'pr'
-        env:
-          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
-          DD_GITHUB_JOB_NAME: ${{ matrix.full_name }}
-        run: ./build/citool/debug/citool upload-build-metrics build/cpu-usage.csv
+  #         # Get closest bors merge commit
+  #         PARENT_COMMIT=`git rev-list --author='bors@rust-lang.org' --author='122020455+rust-bors\[bot\]@users.noreply.github.com' -n1 --first-parent HEAD^1`
+
+  #         ./build/citool/debug/citool postprocess-metrics \
+  #             --job-name ${CI_JOB_NAME} \
+  #             --parent ${PARENT_COMMIT} \
+  #             ${METRICS} >> ${GITHUB_STEP_SUMMARY}
+
+  #     - name: upload job metrics to DataDog
+  #       # This step is not critical, and if some I/O problem happens, we don't want
+  #       # to cancel the build.
+  #       continue-on-error: true
+  #       if: needs.calculate_matrix.outputs.run_type != 'pr'
+  #       env:
+  #         DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
+  #         DD_GITHUB_JOB_NAME: ${{ matrix.full_name }}
+  #       run: ./build/citool/debug/citool upload-build-metrics build/cpu-usage.csv
 
   # This job is used to publish toolstate for successful auto builds.
   outcome:
