Update CI for Rust bors

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,3 +1,6 @@
+# Please make sure that the `needs` fields for both `end-success` and `end-failure`
+# are updated when adding new jobs!
+
 name: CI
 on:
   pull_request:
@@ -6,6 +9,8 @@ on:
     - master
     - staging
     - trying
+    - auto
+    - try
 
 env:
   CARGO_INCREMENTAL: 0
@@ -150,3 +155,21 @@ jobs:
 
     - run: npm run package --scripts-prepend-node-path
       working-directory: ./editors/code
+
+  end-success:
+    name: bors build finished
+    if: github.event.pusher.name == 'bors' && success()
+    runs-on: ubuntu-latest
+    needs: [rust, rust-cross, typescript]
+    steps:
+      - name: Mark the job as successful
+        run: exit 0
+
+  end-failure:
+    name: bors build finished
+    if: github.event.pusher.name == 'bors' && (failure() || cancelled())
+    runs-on: ubuntu-latest
+    needs: [rust, rust-cross, typescript]
+    steps:
+      - name: Mark the job as a failure
+        run: exit 1
